<a href="https://colab.research.google.com/github/Kunal988-gif/DataScience/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np



In [10]:
a = np.array([1, 3, 9 , 0, 2])
print(a)



[1 3 9 0 2]


In [15]:
import numpy as np
np_array = np.array([3, 3, 3, 3, 3.3,'hello', False])
print(bool(np_array[-1])) #when a value is passed to a boolean datatype,
#it gives true

a = False
print(bool(a))

True
False


In [22]:
#a = np.zeros(3)
a = np.zeros([2, 3, 4])
print(a)

print(type(a[0][0][0]))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<class 'numpy.float64'>


In [23]:
a = np.full(4, 5, dtype = int)
print(a)

[5 5 5 5]


In [32]:
a = np.arange(2, 8, 4)
print(a)

[2 6]


In [40]:
a =np.linspace(0, 10 , 11, dtype = int)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [62]:
a = np.array([2, 3, 5, 6, 7])

print(a)
print(np.size(a))
print(np.shape(a))

[2 3 5 6 7]
5
(5,)


In [64]:
a = np.random.randint(1, 7, 4)
print(a)

[4 6 2 2]


In [87]:
a = np.random.choice([2, 4, 2, 9], 2)
print(a)

[2 4]


In [101]:
a = np.array([2, 6, 8, 7])
b = np.array([3, 9, 5, 1])

print(a * 2)
print(a + b)
print(a - b)
print(a / b)


[ 4 12 16 14]
[ 5 15 13  8]
[-1 -3  3  6]
[0.66666667 0.66666667 1.6        7.        ]


In [100]:
a = [2, 3, 6, 7]
b = [4, 5, 7, 8]
print(a + b) #concat.
print(a * 2) #writes twice.


[2, 3, 6, 7, 4, 5, 7, 8]
[2, 3, 6, 7, 2, 3, 6, 7]


In [112]:
a = np.random.randint(2, 15, 6)
print(a)
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))

b = a.reshape((3, 2))
print(b)



[ 8  2  8 11  5  9]
2
11
7.166666666666667
8.0
2.9107081994288295
[[ 8  2]
 [ 8 11]
 [ 5  9]]


In [111]:
a = np.array([2, 3, 5 , 7])
b = np.array([3 , 6, 8 ,2])

concat = np.concatenate((a, b))
print(concat)
concat = np.transpose((a, b))
print(concat)

[2 3 5 7 3 6 8 2]
[[2 3]
 [3 6]
 [5 8]
 [7 2]]


In [119]:
a = np.random.randint(2, 15, 6)
b = np.random.randint(1, 19, 6)

print(a)
print(b)

c = np.where(b > 2, b , a)
print(c)

[10  9  3 13 13  5]
[13  6 16 12  5  9]
[13  6 16 12  5  9]


In [133]:
lst = []
for i in range(1,8):
    print("Day",i, ":")
    lst.append(int(input()))

import numpy as np
a = np.array(lst)
print(a)


print("min:",np.min(a))
print("max:",np.max(a))
print("avg:",np.mean(a))
print("meadian:",np.median(a))
print("standard deviation:",np.std(a))

Day 1 :
23
Day 2 :
34
Day 3 :
56
Day 4 :
78
Day 5 :
56
Day 6 :
89
Day 7 :
90
[23 34 56 78 56 89 90]
min: 23
max: 90
avg: 60.857142857142854
meadian: 56.0
standard deviation: 24.31007181883128
