<a href="https://colab.research.google.com/github/Kunal988-gif/DataScience/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np



In [ ]:
a = np.array([1, 3, 9 , 0, 2])
print(a)



[1 3 9 0 2]


In [ ]:
import numpy as np
np_array = np.array([3, 3, 3, 3, 3.3,'hello', False])
print(bool(np_array[-1])) #when a value is passed to a boolean datatype,
#it gives true

a = False
print(bool(a))

True
False


In [ ]:
#a = np.zeros(3)
a = np.zeros([2, 3, 4])
print(a)

print(type(a[0][0][0]))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<class 'numpy.float64'>


In [ ]:
a = np.full(4, 5, dtype = int)
print(a)

[5 5 5 5]


In [ ]:
a = np.arange(2, 8, 4)
print(a)

[2 6]


In [ ]:
a =np.linspace(0, 10 , 11, dtype = int)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
a = np.array([2, 3, 5, 6, 7])

print(a)
print(np.size(a))
print(np.shape(a))

[2 3 5 6 7]
5
(5,)


In [ ]:
a = np.random.randint(1, 7, 4)
print(a)

[4 6 2 2]


In [ ]:
a = np.random.choice([2, 4, 2, 9], 2)
print(a)

[2 4]


In [ ]:
a = np.array([2, 6, 8, 7])
b = np.array([3, 9, 5, 1])

print(a * 2)
print(a + b)
print(a - b)
print(a / b)


[ 4 12 16 14]
[ 5 15 13  8]
[-1 -3  3  6]
[0.66666667 0.66666667 1.6        7.        ]


In [ ]:
a = [2, 3, 6, 7]
b = [4, 5, 7, 8]
print(a + b) #concat.
print(a * 2) #writes twice.


[2, 3, 6, 7, 4, 5, 7, 8]
[2, 3, 6, 7, 2, 3, 6, 7]


In [ ]:
a = np.random.randint(2, 15, 6)
print(a)
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))

b = a.reshape((3, 2))
print(b)



[ 8  2  8 11  5  9]
2
11
7.166666666666667
8.0
2.9107081994288295
[[ 8  2]
 [ 8 11]
 [ 5  9]]


In [ ]:
a = np.array([2, 3, 5 , 7])
b = np.array([3 , 6, 8 ,2])

concat = np.concatenate((a, b))
print(concat)
concat = np.transpose((a, b))
print(concat)

[2 3 5 7 3 6 8 2]
[[2 3]
 [3 6]
 [5 8]
 [7 2]]


In [ ]:
a = np.random.randint(2, 15, 6)
b = np.random.randint(1, 19, 6)

print(a)
print(b)

c = np.where(b > 2, b , a)
print(c)

[10  9  3 13 13  5]
[13  6 16 12  5  9]
[13  6 16 12  5  9]


In [ ]:
scores = []

days = ['mon', 'tues', 'wed', 'thurs','fri', 'sat', 'sun']





#for i in range(1,8):
   #print("Day",i, ":")
   #scores.append(int(input()))

import numpy as np
a = np.array(scores)
print(a)


print("min:",np.min(a))
print("max:",np.max(a))
print("avg:",np.mean(a))
print("meadian:",np.median(a))
print("standard deviation:",np.std(a))

Day 1 :
23
Day 2 :
34
Day 3 :
56
Day 4 :
78
Day 5 :
56
Day 6 :
89
Day 7 :
90
[23 34 56 78 56 89 90]
min: 23
max: 90
avg: 60.857142857142854
meadian: 56.0
standard deviation: 24.31007181883128


In [ ]:
scores = input().split()
print(scores)




In [10]:
weekly_sales = {}

while True:
    item = input().strip().lower()

    if item == "end":
        break

    quantity = int(input(f"How many {item}s were sold?: "))

    if item in weekly_sales:
        weekly_sales[item] += quantity
    else:
        weekly_sales[item] = quantity
    print(f"Recorded: +{quantity} {item}(s)\n")


if not weekly_sales:
    print("No items were sold this week.")
else:
    for item, total_sold in weekly_sales.items():
        print(f"• {item.capitalize()}: {total_sold} sold")


bhujia
How many bhujias were sold?: 1
Recorded: +1 bhujia(s)

karela chips
How many karela chipss were sold?: 1
Recorded: +1 karela chips(s)

nimbu
How many nimbus were sold?: 250
Recorded: +250 nimbu(s)

puchhiii
How many puchhiiis were sold?: 10
Recorded: +10 puchhiii(s)

uska pyaar
How many uska pyaars were sold?: 1
Recorded: +1 uska pyaar(s)

end
• Bhujia: 1 sold
• Karela chips: 1 sold
• Nimbu: 250 sold
• Puchhiii: 10 sold
• Uska pyaar: 1 sold


In [38]:
#q1:
a = np.random.randint(1, 90,(5, 5))
print(a)

print("\n")

row_mean = np.mean(a, axis = 1)
print(row_mean)

print("\n")

col_mean = np.mean(a, axis = 0)
print(col_mean)

print("\n")

replace = np.where(a % 2 == 0, -1, a)
print(replace)

print("\n")

sort_row = np.sort(a, axis = 1)
print(sort_row)

print("\n")

sort_col = np.sort(a, axis = 0)
print(sort_col)

print("\n")

row_wise_sum = np.sum(a, axis = 1)
print(row_wise_sum)

print("\n")

col_wise_sum = np.sum(a, axis = 0)
print(col_wise_sum)

print("\n")

cnt = 0


cnt_neg = np.count_nonzero(replace < 0)

print(cnt_neg)





[[59  4 57 21 45]
 [49 47 80 44 51]
 [60  9 62 40 17]
 [76 27 37  7 50]
 [58 84 16 76 17]]


[37.2 54.2 37.6 39.4 50.2]


[60.4 34.2 50.4 37.6 36. ]


[[59 -1 57 21 45]
 [49 47 -1 -1 51]
 [-1  9 -1 -1 17]
 [-1 27 37  7 -1]
 [-1 -1 -1 -1 17]]


[[ 4 21 45 57 59]
 [44 47 49 51 80]
 [ 9 17 40 60 62]
 [ 7 27 37 50 76]
 [16 17 58 76 84]]


[[49  4 16  7 17]
 [58  9 37 21 17]
 [59 27 57 40 45]
 [60 47 62 44 50]
 [76 84 80 76 51]]


[186 271 188 197 251]


[302 171 252 188 180]


[[59  1 57 21 45]
 [49 47  1  1 51]
 [ 1  9  1  1 17]
 [ 1 27 37  7  1]
 [ 1  1  1  1 17]]


In [51]:
stock = np.random.randint(20, 80,(5,5))
print(stock)

print("\n")

demand = np.random.randint(20, 80, (5, 5))
print(demand)

print("\n")

#remaining stock:

remaining_stock = stock -  demand
print(remaining_stock)
print("\n")

#neg_values -> 0

replace = np.where(remaining_stock < 0, 0, remaining_stock)
print(replace)
print("\n")

#total shortage:
total_shortage = np.sum(np.where(remaining_stock < 0, -remaining_stock, 0))
print(total_shortage)
print("\n")

#products with zero stock:
zero_stock = np.sum(remaining_stock < 0)
print(zero_stock)
print("\n")

#sort each row based on remaing stock
sort_row = np.sort(remaining_stock, axis = 1)
print(sort_row)
print("\n")

[[47 65 73 62 50]
 [57 50 37 23 30]
 [56 52 70 46 55]
 [20 65 70 30 73]
 [56 66 20 64 72]]


[[38 72 28 75 33]
 [50 24 64 34 22]
 [20 37 35 77 75]
 [55 47 62 21 56]
 [71 44 66 77 33]]


[[  9  -7  45 -13  17]
 [  7  26 -27 -11   8]
 [ 36  15  35 -31 -20]
 [-35  18   8   9  17]
 [-15  22 -46 -13  39]]


[[ 9  0 45  0 17]
 [ 7 26  0  0  8]
 [36 15 35  0  0]
 [ 0 18  8  9 17]
 [ 0 22  0  0 39]]


218


10


[[-13  -7   9  17  45]
 [-27 -11   7   8  26]
 [-31 -20  15  35  36]
 [-35   8   9  17  18]
 [-46 -15 -13  22  39]]


